
predictors = [
    'Battles (t-1)',
    'Explosions/Remote violence (t-1)',
    'Protests (t-1)',
    'Riots (t-1)',
    'Strategic developments (t-1)',
    'Violence against civilians (t-1)',
    'Excessive force against protesters (t-1)',
    'Agreement (t-1)',
    'Explosions/Remote violence_neighbours (t-1)',
    'Strategic developments_neighbours (t-1)',
    'Protests_neighbours (t-1)',
    'Violence against civilians_neighbours (t-1)',
    'Battles_neighbours (t-1)',
    'Riots_neighbours (t-1)',
    'linear_month_trend',
    'year',
    'month_2',
    'month_3',
    'month_4',
    'month_5',
    'month_6',
    'month_7',
    'month_8',
    'month_9',
    'month_10',
    'month_11',
    'month_12',
    'quarter_2',
    'quarter_3',
    'quarter_4',
    "inflation (t-1)",
    "youth_unemployment (t-1)",
    "income_inequality (t-1)",
    "income_level_code",
    'christian_holiday_count',
    'islam_holiday_count',
    'shia_holiday_count',
    'hindu_holiday_count',
    'buddhist_holiday_count',
    'jewish_holiday_count',
    'cultural_holiday_count',
    'nonreligious_holiday_count',
    'christian_holiday_count (t-1)',
    'islam_holiday_count (t-1)',
    'shia_holiday_count (t-1)',
    'hindu_holiday_count (t-1)',
    'buddhist_holiday_count (t-1)',
    'jewish_holiday_count (t-1)',
    'cultural_holiday_count (t-1)',
    'nonreligious_holiday_count (t-1)',
    'majority_religion',
    'majority_pct',
    'minority1_religion',
    'minority1_pct',
    'minority2_religion',
    'minority2_pct',
    'nonreligpct',
    'weighted_holidays_majority',
    'weighted_holidays_minority1',
    'weighted_holidays_minority2',
    'minority_tension_minority1',
    'minority_tension_minority2',
    'minority_tension_total',
    'total_religious_mobilization',
    'weighted_holidays_majority (t-1)',
    'weighted_holidays_minority1 (t-1)',
    'weighted_holidays_minority2 (t-1)',
    'minority_tension_minority1 (t-1)',
    'minority_tension_minority2 (t-1)',
    'minority_tension_total (t-1)',
    'total_religious_mobilization (t-1)',
    "structural_vulnerability",
    "inflation_shock",
    "shock_vulnerability",
    "capacity_adjusted_risk",
    "inflation_change",
    "high_inequality_flag",
    "inflation_shock_poor",
    "conflict_momentum",
    "violence_escalation",
    "macro_conflict_pressure",] 

targets = [
    'Battles',
    'Explosions/Remote violence',
    'Violence against civilians'
    ]